version: "3.1"

services:
  db:
    container_name: TODO-db
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: password

volumes:
  db-data:
